### ISSUE TITLE
Iso Range

### ISSUE THREAD

**Issue by jst84** [AOT-AG/DicomToMesh#12]
Hi, is it possible to set iso (density) as a range.
For example, if I want to view only the aorta and not all the body, how I can do this?

Thanks,
Stefano.

**Comment by eidelen** [comment]
Hi Stefano,
This is not implemented yet. Actually, that would be a good feature. Thank you for the idea. I will make a note and implement it, as soon I'm working on dicom2mesh again.
In the meantime, you could use the volume rendering (option -vo) and set solely the particular range. However, you cannot export it as a surface mesh.
Regards,
Adrian

**Comment by eidelen** [comment]
Hi Stefano,
This option is now available. The option name is **-tu**
`dicom2mesh -i pathToDicomDirectory  -o abc.obj  -t 500 -tu 900 `

**Comment by jst84** [comment]
Wonderful!
Thanks a lot :)

**Comment by jst84** [comment]
eidelen sorry but i cannot build on windows:
![image](https://user-images.githubusercontent.com/25516048/47211001-b16aff00-d394-11e8-899b-dd82657df36f.png)
could you help me?

**Comment by aneeshikmat** [comment]
@eidelen Really its Wonderful Library. I like it. Thank you. 

I would ask about IsoRange, I build obj file for CT-scan by reading DICOM image..and set **ISO from 200 to 400** ... and all its okay...but my question is theres any way to know what it is current range for voxels in obj file? Since I need to read it to render only iso 200, or only 300 ....etc From range obj exported file. (My idea is build slider by unreal engine to read voxel ranges) ...so that which algorithm/math or rule I most do to I can got it. Thanks a lot.

**Comment by eidelen** [comment]
@aneeshikmat Thank you. But the workhorse is vtk. We just call their functions.

The ISO range is not in the obj file. But it is written to the info file. Let's assume you export an obj file with name "abcd.obj". In the same directory you will find a file called "abcd.info", which contains the segmentation range.
`Surface segmentation: 200 to 400`

**Comment by eidelen** [comment]
Hi Stefano,
If you agree, I close this issue? 
Regards,
Adrian
